# Config file for continuous integration.

[rust]
codegen-units = 0           # Use many compilation units.
debug-assertions = true     # Turn on assertions in rustc.

[llvm]
assertions = true           # Turn on assertions in LLVM.
